---
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6
    command:
      - start-dev
      - --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      kind:
        aliases:
          - keycloak.localtest.me
    volumes:
      - type: bind
        source: ./keycloak-realm.json
        target: /opt/keycloak/data/import/realm.json
        read_only: true

networks:
  kind:
    name: kind
    external: true
