---
apiVersion: v2
name: netbird
description: NetBird VPN management platform
type: application
version: 0.14.2
appVersion: "0.26.3"
icon: https://avatars.githubusercontent.com/u/100464677
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: updated to 0.26.3
