apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" . }}-management
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  {{- if not .Values.management.autoscaling.enabled }}
  replicas: {{ .Values.management.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netbird.management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/management-cm.yaml") . | sha256sum }}
        {{- with .Values.management.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "netbird.management.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.management.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.management.podSecurityContext | nindent 8 }}
      initContainers:
        - name: configure
          image: golang:latest
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              go install github.com/drone/envsubst/cmd/envsubst@latest &&
              envsubst < /tmp/netbird/management.tmpl.json > /etc/netbird/management.json &&
              cat /etc/netbird/management.json
          env:
            # General configuration.
            - name: NETBIRD_DOMAIN
              value: {{ .Values.domain | quote }}

            # STUN and TURN configuration.
            - name: TURN_DOMAIN
              value: {{ .Values.turn.domain | quote }}
            - name: TURN_USER
              value: {{ default "" .Values.turn.user | quote }}
            {{- with .Values.turn.secretKeyRef }}
            - name: TURN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- else }}
            - name: TURN_PASSWORD
              value: ""
            {{- end }}

            # Relay Configuration
            - name: NETBIRD_RELAY_ENDPOINT
              value: {{ .Values.relay.endpoint | quote }}
            {{- with .Values.relay.secretKeyRef }}
            - name: NETBIRD_RELAY_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- else }}
            - name: NETBIRD_RELAY_AUTH_SECRET
              value: ""
            {{- end }}

            # Signal Configuration
            - name: NETBIRD_SIGNAL_PORT
              value: {{ .Values.signal.port | quote }}
            - name: NETBIRD_SIGNAL_PROTOCOL
              value: {{ .Values.signal.protocol | quote }}

            - name: NETBIRD_MGMT_DISABLE_DEFAULT_POLICY
              value: {{ .Values.disableDefaultPolicy | quote }}

            {{- with .Values.datastore.encryptionKey.secretKeyRef }}
            - name: NETBIRD_DATASTORE_ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- else }}
            - name: NETBIRD_DATASTORE_ENC_KEY
              value: ""
            {{- end }}

            - name: NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT
              value: {{ default (printf "%s/.well-known/openid-configuration" .Values.auth.authority) .Values.auth.oidcConfigEndpoint | quote }}
            - name: NETBIRD_MGMT_API_CERT_FILE
              value: {{ .Values.management.tls.certFile | quote }}
            - name: NETBIRD_MGMT_API_CERT_KEY_FILE
              value: {{ .Values.management.tls.certKeyFile | quote }}
            - name: NETBIRD_MGMT_API_PORT
              value: {{ .Values.management.service.port | quote }}
            - name: NETBIRD_MGMT_IDP_SIGNKEY_REFRESH
              value: {{ .Values.management.idpSignKeyRefreshEnabled | quote }}
            - name: NETBIRD_AUTH_AUTHORITY
              value: {{ .Values.auth.authority | quote }}
            - name: NETBIRD_AUTH_AUDIENCE
              value: {{ .Values.auth.audience | quote }}
            - name: NETBIRD_AUTH_JWT_CERTS
              value: {{ .Values.auth.jwtCerts | quote }}
            - name: NETBIRD_AUTH_TOKEN_ENDPOINT
              value: {{ .Values.auth.tokenEndpoint | quote }}
            - name: NETBIRD_AUTH_USER_ID_CLAIM
              value: {{ .Values.auth.userIDClaim | quote }}

            - name: NETBIRD_IDP_MGMT_CLIENT_ID
              value: {{ default "" .Values.idp.clientID | quote }}
            {{- if .Values.idp.secretKeyRef }}
            {{- with .Values.idp.secretKeyRef }}
            - name: NETBIRD_IDP_MGMT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            {{- else }}
            - name: NETBIRD_IDP_MGMT_CLIENT_SECRET
              value: {{ default "" .Values.idp.clientSecret | quote }}
            {{- end }}
            - name: NETBIRD_IDP_MGMT_EXTRA_CONFIG
              {{- if .Values.idp.extraConfig }}
              value: {{ .Values.idp.extraConfig | toJson | quote }}
              {{- else if eq .Values.idp.managerType "keycloak" }}
              value: {{ dict "AdminEndpoint" .Values.idp.adminEndpoint | toJson | quote }}
              {{- else }}
              value: "{}"
              {{- end }}

            # Device auth configuration.
            - name: NETBIRD_AUTH_DEVICE_AUTH_PROVIDER
              value: {{ .Values.auth.device.provider | quote }}
            - name: NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE
              value: {{ default "" .Values.auth.device.audience | quote }}
            - name: NETBIRD_AUTH0_DOMAIN
              value: {{ default "" .Values.auth.device.auth0Domain | quote }}
            - name: NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID
              value: {{ default "" .Values.auth.device.clientID | quote }}
            - name: NETBIRD_AUTH_DEVICE_AUTH_ENDPOINT
              value: {{ default "" .Values.auth.device.deviceAuthorizationEndpoint | quote }}
            - name: NETBIRD_AUTH_DEVICE_AUTH_SCOPE
              value: {{ default "openid" .Values.auth.device.scope | quote }}
            - name: NETBIRD_AUTH_DEVICE_AUTH_USE_ID_TOKEN
              value: {{ default false .Values.auth.device.useIDToken | quote }}

            # IDP configuration.
            - name: NETBIRD_MGMT_IDP
              value: {{ .Values.idp.managerType | quote }}

            # Database Configuration
            - name: NETBIRD_STORE_CONFIG_ENGINE
              {{- if .Values.management.database.postgres }}
              value: postgres
              {{- else }}
              value: sqlite
              {{- end }}

            # PKCE auth configuration.
            - name: NETBIRD_AUTH_PKCE_AUDIENCE
              value: {{ default .Values.auth.audience .Values.auth.pkce.audience | quote }}
            - name: NETBIRD_AUTH_CLIENT_ID
              value: {{ .Values.auth.clientID | quote }}
            {{- if .Values.auth.secretKeyRef }}
            {{- with .Values.auth.secretKeyRef }}
            - name: NETBIRD_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            {{- else }}
            - name: NETBIRD_AUTH_CLIENT_SECRET
              value: {{ .Values.auth.clientSecret | quote }}
            {{- end }}
            - name: NETBIRD_AUTH_PKCE_AUTHORIZATION_ENDPOINT
              value: {{ .Values.auth.pkce.authorizationEndpoint | quote }}
            - name: NETBIRD_AUTH_SUPPORTED_SCOPES
              value: {{ .Values.auth.pkce.scope | quote }}
            - name: NETBIRD_AUTH_PKCE_REDIRECT_URLS
              {{- $redirectURLs := list -}}
              {{- range .Values.auth.pkce.redirectURLs }}
              {{- $redirectURLs = append $redirectURLs (. | quote) }}
              {{- end }}
              value: {{ join "," $redirectURLs | quote }}
            - name: NETBIRD_AUTH_PKCE_USE_ID_TOKEN
              value: {{ .Values.auth.pkce.useIDToken | quote }}
            - name: NETBIRD_AUTH_PKCE_DISABLE_PROMPT_LOGIN
              value: {{ .Values.auth.pkce.disablePromptLogin | quote }}
            - name: NETBIRD_AUTH_PKCE_LOGIN_FLAG
              value: {{ .Values.auth.pkce.loginFlag | quote }}

          volumeMounts:
            - mountPath: /etc/netbird
              name: config
            - mountPath: /tmp/netbird
              name: config-template
      containers:
        - name: {{ .Chart.Name }}-management
          securityContext:
            {{- toYaml .Values.management.securityContext | nindent 12 }}
          image: "{{ .Values.management.image.repository }}:{{ .Values.management.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          args:
            - --log-level
            - {{ .Values.management.logLevel }}
            - --log-file
            - console
            - --dns-domain
            - {{ .Values.management.dnsDomain }}
          {{- if .Values.management.database.postgres }}
          env:
            - name: NETBIRD_STORE_ENGINE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.management.database.postgres.dsnSecret.name }}
                  key: {{ .Values.management.database.postgres.dsnSecret.key }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.management.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.management.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/netbird
              name: config
            - mountPath: /var/lib/netbird
              name: management
      {{- with .Values.management.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          emptyDir:
            medium: Memory
        - name: config-template
          configMap:
            name: {{ include "netbird.fullname" . }}-management
        - name: management
          {{- if .Values.management.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "netbird.fullname" . }}-management
          {{- else }}
          emptyDir: {}
          {{- end }}
