apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-relay
  labels:
    {{- include "netbird.relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netbird.relay.selectorLabels" . | nindent 4 }}
