apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-signal
  labels:
    {{- include "netbird.signal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.signal.service.type }}
  ports:
    - port: {{ .Values.signal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netbird.signal.selectorLabels" . | nindent 4 }}
