---
name: dagger

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"

permissions:
  contents: read

jobs:
  dagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"
      - name: dagger
        run: go run ci.go
